# Generated by Django 2.0.5 on 2018-11-22 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField()),
                ('hora_salida', models.DateTimeField()),
                ('estado_control', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(max_length=20)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('categoria_proveedor', models.ManyToManyField(to='proveedor.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_puesto', models.CharField(max_length=50)),
                ('representante_puesto', models.CharField(max_length=50)),
                ('ubicacion_puesto', models.CharField(max_length=50)),
                ('categoria_puesto', models.ManyToManyField(to='proveedor.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='proveedor',
            name='puesto_proveedor',
            field=models.ManyToManyField(to='proveedor.Puesto'),
        ),
        migrations.AddField(
            model_name='control',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.Proveedor'),
        ),
    ]
