# Generated by Django 2.0 on 2018-11-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_auto_20181122_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='fecha_entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
