# Generated by Django 2.0 on 2019-01-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0006_control_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_administrador', models.CharField(max_length=20)),
            ],
        ),
    ]
